learning_rate:
  type: float
  min: 1.0e-4
  max: 3.0
  log_space: True
max_grad_norm:
  type: float
  min: 1.0e-5
  max: 20.0
  log_space: True
bsr_bands:
  type: ordered
  options:
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 100
bnb_bands:
  type: ordered
  options:
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 100
