# Custom metrics for the EyePACS diabetic-retinopathy tutorials.
#
# EyePACS is heavily class-imbalanced, thus AUROC is added here as a more sensitive metric in this particular case.
#
# The built-in MulticlassAccuracy variants are always computed in addition to whatever is listed here.
# to whatever is listed here.

train_metrics:
  - name: AUROC
    params:
      average: macro

valid_metrics:
  - name: AUROC
    params:
      average: macro

test_metrics:
  - name: AUROC
    params:
      average: macro
